### ISSUE TITLE
Unity 2018.2+ deprecates Networking API

### ISSUE THREAD

**Issue by partlyhuman** [gwaredd/unium#11]
Updating Unium for Unity 2018 might require some refactoring. Ignoring errors in sample code, compile errors stem from the `UnityEngine.Network` API being deprecated.

e.g. ```Assets/Unium/UniumComponent.cs(118,65): error CS0619: `UnityEngine.Network.player' is obsolete: `The legacy networking system has been removed in Unity 2018.2. Use Unity Multiplayer and NetworkIdentity instead.'```

![image](https://user-images.githubusercontent.com/327136/40676944-0f808bca-6331-11e8-94be-ea5941d553ce.png)

**Comment by gwaredd** [comment]
I never was a fan of that interface anyway. I've replaced the call with a more vanilla version in the dev branch. I won't merge it into main until I've had a chance to test it across various platforms and unity versions though but it's there if you want a sneak peak.

**Comment by gwaredd** [comment]
Done
