### ISSUE TITLE
utils/screenshot is failed on mobile device.

### ISSUE THREAD

**Issue by yuewah** [gwaredd/unium#12]
On mobile platforms the filename is appended to the persistent data path.
https://docs.unity3d.com/ScriptReference/Application.CaptureScreenshot.html

 Application.CaptureScreenshot( filename ) should not contain full path for mobile device build.

**Comment by gwaredd** [comment]
Good catch. Also looks like Application.CaptureScreenshot is being deprecated in favour of ScreenCapture.CaptureScreenshot. I am away for a bit so may take a couple of weeks before I get a chance to look at it.

**Comment by sp-bertrand-carre** [comment]
I didn't opened a pull request, but as a quick fix you can use the following code, that basically takes a screenshot in memory.
[HandlerUtils.cs.txt](https://github.com/gwaredd/unium/files/2102565/HandlerUtils.cs.txt)

**Comment by yuewah** [comment]
So, you prefer take screenshot in memory instead of using unity builtin api?

**Comment by sp-bertrand-carre** [comment]
Yes, unity builtin API for screenshot might be more optimal for getting the screenshot, but it only saves on "disk", and I don't need the "save" and "reload" from "disk" part (which is slow).

**Comment by yuewah** [comment]
I agree.

**Comment by gwaredd** [comment]
Sounds good, let's add it :)

**Comment by gwaredd** [comment]
Now added to the project and merged into main. Cheers
