### ISSUE TITLE
[FeatureRequest] Get the scene hierarchy tree json

### ISSUE THREAD

**Issue by yuewah** [gwaredd/unium#13]
I would like to make a interactive treeview ui for unity gameobject hierarchy on web browser. However, most of the javascript treeview ui supports hierarchy tree json instead of the flat json that returned by Unium GQL.
The following is hierarchy tree json example.
e.g. ` [
                {
                "name": "Parent",
                "children": [
                    {
                    "name": "Child1",
                    "children": []
                    },
                    {
                    "name": "Child2",
                    "children": [
                         {
                            "name": "Child2_1",
                            "children": []
                        }
                    ]
                    }
                ]
                }
            ]`

**Comment by gwaredd** [comment]
The GQL search returns a list of all nodes that match the query, so conceptually this is inherently flat and not going to change.

However the reflection part doesn't have to be necessarily. As this might take me some time to get around to, if you wanted to implemented it yourself you could look at modifying the `SerialiseGameObject.Convert` function, around line 61. If you recursively call the function and add it to the json it should give you what you want (although you may also have to modify the JsonBuilder or pass it down in the call).

Alternatively, you could modify `InterpreterGameObject.Attr` to add a dummy 'path' attribute to the game object and call `UniumUtils.Path` which will give you the 'url' of that object.

Then if you query `/q/scene//*.path` to get the tree as a a flat list, you can reconstruct the tree structure on the client side. Should be relatively straightforward.

It's an interesting feature, I shall give it some thought.

**Comment by gwaredd** [comment]
I've added the 'path' attribute to the library, as this is the least intrusive option. Note the path includes a unique object index (the numbers after the @), which is required as objects can have the same name.

It's pretty straightforward to convert the flat list to a hierarchical structure, see [this gist](https://gist.github.com/gwaredd/cf6162e8067aa9c33169118f395924c4) which uses the lodash.js library. 

Might be a little confusing if you're not used to functional style programming but hopefully makes some kind of sense.

Hope that helps

G

**Comment by yuewah** [comment]
Thx, I can render the tree structure using jsTree UI component. 
However, if I select one of the tree node, I want to get selected unity gameobject properties, but it can't.
How can I query it by e.g.  /q/scene/Game@1:2/Cube@1:4/Test2@1:0 ?

**Comment by gwaredd** [comment]
GQL doesn't support the "@" bit, so the 'path' isn't actually a valid GQL query. However, you have the tree structure you can create the URL as if you would in a directory structure - except one where files can have the same name (in which case you need to specify which one).

For example, say you had a scene hierarchy of ...

```
Game
  +- Sphere
  +- Cube
       +- Test
  +- Cube
  +- Cube
       +- Test
  +- Cube
  +- Capsule
```

Then the path of the second Test object would be ...

`/q/scene/Game/Cube[2]/Test`

Cube[2] as it's 0 indexed. So you can find the path by just walking up the tree and comparing siblings with the same name

**Comment by yuewah** [comment]
I modify InterpreterGameObject.Attr to add a dummy 'gid' attribute to the game object 
`if (name == "gid")
 {
 return go.GetInstanceID();
 }`
And UniumUtils.Path return xf.gameObject.GetInstanceID()
Then we can select the specific gameobject instance.
/q/scene//*[gid=600]

**Comment by gwaredd** [comment]
That sounds like a better solution :) Do you have a pull request?

**Comment by gwaredd** [comment]
I much prefer that solution, although made a couple of minor changes (iid rather than gid) and now paths use [iid=...] in the format so they are both unique and valid GQL.

Thanks

**Comment by yuewah** [comment]
I see you changed the format and value for .path , is it still work for PathsToTree.js ?

**Comment by gwaredd** [comment]
It will still work but you will want to clean up the names by removing the `[...]` bit.

So change [this line](https://gist.github.com/gwaredd/cf6162e8067aa9c33169118f395924c4#file-pathstotree-js-L20) ... 

From

    `name: k.replace( /@.*/, '' ),`

To

    `name: k.replace( /\[.*/, '' ),`

**Comment by kongguliu** [comment]
Have you solved it? I wrote some code to implement it. I have already got the complete tree, but the format displayed on the webpage is wrong. Can you help me with it? Thank you！
![image](https://user-images.githubusercontent.com/18191658/55865582-3d761a80-5bb1-11e9-804e-e97627521260.png)

**Comment by kongguliu** [comment]
Have you solved it? I wrote some code to implement it. I have already got the complete tree, but the format displayed on the webpage is wrong. Can you help me with it? Thank you
the tree show on the webpage like this：
"[{\"name\":\"Sphere\",\"tag\":\"Untagged\",\"activeInHierarchy\":true,\"components\":[\"Transform\",\"MeshFilter\",\"MeshRenderer\",\"SphereCollider\"],\"children\":[\"Cube\",\"children\":[],\"Cube (1)\",\"children\":[\"Sphere (2)\",\"children\":[\"Cube\",\"children\":[],\"Cube (1)\",\"children\":[]]]]}]"
![image](https://user-images.githubusercontent.com/18191658/55865852-c4c38e00-5bb1-11e9-92b5-575cd03d9042.png)
![image](https://user-images.githubusercontent.com/18191658/55865865-cab96f00-5bb1-11e9-8745-cb845d51bfa2.png)
