### ISSUE TITLE
GQL cannot find DontDestroyOnLoad objects

### ISSUE THREAD

**Issue by partlyhuman** [gwaredd/unium#14]
Because the `/scene` endpoint evaluates all root objects on all loaded scenes, it actually fails to catch objects that have set DontDestroyOnLoad in its net. These objects in a sense don't live in a scene. I am trying to think of a more elegant solution for this than iterating through `FindObjectsOfTypeAll<Transform>()`, mapping to the root of the transform hierarchy, and taking only unique entries, but at the moment coming short. If there's a way to do this more efficiently that'd be ideal. Of course this might also be another reason to consider more specific endpoints in addition to `/scene/`, so that you can have the old and efficient behaviour with `/scene/` and more power/less efficiency when you need it.

**Comment by gwaredd** [comment]
There's a component called UniumRegister that can be added to a game object that will register it with the GQL root (/q rather than /q/scene).

This should work even if it's in DontDestroy group

**Comment by gwaredd** [comment]
So UniumRegister is convenient for exposing one or two objects that are useful.

If you wanted all the DontDestroy objects to be treated as a scene in their own right you can call UniumComponent.Singleton.gameObject.scene.GetRootGameObjects(). Works on the fact that the game object with the UniumComponent is also in that group. This will work in editor, I'd have to try it on a build though.

So you could just add these to the scene object in the GQL root ...

**Comment by partlyhuman** [comment]
That is extremely clever! And leagues more efficient so this might be a good fix.

**Comment by gwaredd** [comment]
Done
