### ISSUE TITLE
How can we execute test in clould devices?

### ISSUE THREAD

**Issue by archanapura** [gwaredd/unium#17]
Does unium supports cloud testing?

**Comment by gwaredd** [comment]
Yes. 

Unium is just a webserver, so if there is a network path from test machine to device it doesn't matter where it runs. 

Are you having any issues specifically?

**Comment by archanapura** [comment]
Thank you,I tried in real device and it worked if device and PC are in same network(wifi)
If I need to connect to emulators,How can I connect system and emulators in same network.

**Comment by gwaredd** [comment]
Closing, see #36
