### ISSUE TITLE
Running Unium on Android

### ISSUE THREAD

**Issue by sapanda** [gwaredd/unium#2]
I've been trying to run the Unium Tutorial on my Android device but without success. I noticed that you had some Android-specific code in there so was wondering if you have any advice on troubleshooting the issue.

Here's my setup:
1) Both Mac & Android device are on the same Wifi network
2) Unium Tutorial running on Android
3) Run the following command from my Mac:
```
$curl http://10.9.105.223:8080/about
curl: (7) Failed to connect to 10.9.105.223 port 8080: Connection refused
```

I tried a couple things:
1) `UniumComponent.StartServer()` overrides the `Settings.Address` for non-editor apps. I changed it to always force the Address to `IPAddress.Any`.
2) Tried several other ports. I'm always able to hit a server running on my Mac from the phone, but not the other way around.

(PS: Thanks for this awesome tool, it's exactly what we've been looking for! We think it's going to change how we approach testing. Planning on leaving a review on the asset store once we get this up and running!)

Thanks,
Saswat

**Comment by gwaredd** [comment]
Hey,

I've tested this on my Galaxy S8 and it appears to working fine. There are a couple of things you could check though that might be tripping you up.

The code by default will be compiled out for release builds, so check that the "development build" flag is set when you are making a build (alternatively, defining "UNIUM_ENABLE" as a build symbol will enable the code for all build flavours).

By default the listening port is 8342, although you can change this on the UniumComponent.

Let me know if that helps :)

Gw

**Comment by sapanda** [comment]
Of course... Embarrassing, forgot to enable "Development Build" when I spun up the new project. Thanks, works like a charm now!
