### ISSUE TITLE
Is it possible to integrate with e.g. Katalon test framework?

### ISSUE THREAD

**Issue by petrahietaniemi** [gwaredd/unium#25]
It is mentioned in the Unity Asset store: "It embeds a web server into debug builds of your project which provides an interface and a query language the enables you to remotely control your game. This means you can use your favourite testing frameworks to write automated tests."

Does it mean that you could integrate with e.g. Katalon?

**Comment by gwaredd** [comment]
Well I don't know much about Katalon but yes, I imagine you could integrate it.
