### ISSUE TITLE
Screenshot does not match what is shown on screen

### ISSUE THREAD

**Issue by hiaw** [gwaredd/unium#26]
![screen shot 2018-09-24 at 12 22 27 pm](https://user-images.githubusercontent.com/527296/45934611-89d28200-bff4-11e8-8508-3680df0d129f.png)
![test](https://user-images.githubusercontent.com/527296/45934612-8ccd7280-bff4-11e8-8d7a-1e24711b8e60.png)

The first image is from the game screen and the second image is what's captured.

**Comment by gwaredd** [comment]
It looks like this is [intended behaviour from Unity](https://issuetracker.unity3d.com/issues/rendertextures-do-not-include-canvas-ui-elements).

I will look into it but in the meantime I've re-added the previous screenshot code that uses `ScreenCapture.CaptureScreenshot` to the end point `/utils/appscreenshot`

HTH, Gw
