### ISSUE TITLE
TUTORIAL - calling action MoveTo gives null response

### ISSUE THREAD

**Issue by silmysnatch** [gwaredd/unium#27]
In the tutorial scene, GQL Action triggering MoveTo method does not receive a proper response, which is the new values.

**Comment by gwaredd** [comment]
[null] is the correct response :) Although might be a little confusing as to why.

[MoveTo](https://github.com/gwaredd/unium/blob/f8f7c31c08f9c31f39a572fd1d62a71028bade5a/Assets/Tutorial/Scripts/Player.cs#L18)() is a function with no return value (void).

When a query invokes a function it returns the return value of that function (technically a list of all functions invoked by the query as you can select multiple objects). If there is no return value it substitutes 'null' as this seems to be the most appropriate valid JSON value.

So in this case there is only one function called so the result is a list of one value, null.

If you want the values back, just return them, i.e.

```
public Vector3 MoveTo( Vector3 pos )
{
    agent.destination = pos;
    return pos;
}
```

Hope that makes sense ...

**Comment by gwaredd** [comment]
I may have misunderstood the issue though. When you say receive a response, do you mean the tutorial doesn't work? :) I've tested the head revision against untiy v5.4.2 and v2018.2.9 and seems to work for me, so let me know ... cheers

**Comment by silmysnatch** [comment]
oh yes, it works fine. As I remember for reading the tutorial (not the pdf), it says that invoking the function will return the value. So I thought it should return back the vector3 position,

However, after reading the pdf, it says clearly that it could return null if it's a void function. My mistake then. Thank you for your kind explanation :)
