### ISSUE TITLE
can't query the path to a prefab having space in its name in localhost

### ISSUE THREAD

**Issue by shamsher786** [gwaredd/unium#28]
Example- http://localhost:13000/q/scene/HomeScaler/Canvas/Nav Bar
I cannot access the tree inside Nav Bar

**Comment by gwaredd** [comment]
Does putting `%20` in place of the space character work? i.e.

[http://localhost:13000/q/scene/HomeScaler/Canvas/Nav%20Bar](http://localhost:13000/q/scene/HomeScaler/Canvas/Nav%20Bar)

**Comment by shamsher786** [comment]
No it did not work

**Comment by gwaredd** [comment]
There should be no problem with spaces in names of objects so long as the URL is being encoded correctly. It works for me :)

Do you have a test scene I can try?

**Comment by shamsher786** [comment]
It does work with object but did not work with prefab @gwaredd
