### ISSUE TITLE
Can't update property value contains \n

### ISSUE THREAD

**Issue by yuewah** [gwaredd/unium#29]
http://localhost:8342/q/scene/GameObject1.TextMesh.text=Line%0ALine2 
it will cut the %0ALine2 where %0A is '\n'

It can be fix by adding RegexOptions.Singleline in Path.cs
  static Regex sMatchToken = new Regex(
            @"(?<type>[/\.])" + 
            @"(?<name>[^\[\]\./=\(]+)?" + 
            @"(\[(?<where>[^\]]+)\])?" +
            @"(?<action>(=|\()(?<params>.*))?"
	    , RegexOptions.Singleline
            // enable regex compilation if using the full .net API compatibility (much faster!)
            #if NET_2_0
            | RegexOptions.Compiled
            #endif
        );

**Comment by gwaredd** [comment]
cheers
