### ISSUE TITLE
Cannot detect the element in IOS

### ISSUE THREAD

**Issue by sanjusangal** [gwaredd/unium#31]
I am trying to perform some click operations on a ios build. The same code works fine with Andriod but not with iOS. Does unium support ios?
I have used unium as a bridge between appium and app. I have also setup xcuitest driver. 
I am able to install and launch the application but cannot perform operations in app.
I am trying to inspect the element the element using phone ip 
Ex: 10.0.0.59:13000/q/scene/canvas/button
Browser cannot detect the element.

**Comment by gwaredd** [comment]
Hi, yes unium suports iOS.

There is no platform dependent code in the library so there should be no difference between iOS and Android (with a minor exception of the /file route). 

I presume you can access the device in your browser? (e.g. http://10.0.0.59:13000/about works).

You could try walking the scene in your browser - start with /q/scene and see what objects are visible (outside of appium and xcuitest driver).

**Comment by gwaredd** [comment]
Hey,

It works fine on my test device so my guess is if you were to point your browser to a different interface it might work. I find the 10.0.0.X addresses don't work for me (C# lists both 10.X.X.X and 192.168.X.X addresses when I enumerate the interface list)

The code isn't doing anything special, it's just a standard C# raw socket TcpListener, see Unium\Core\gw.proto.http\Server.cs.

iOS actually has many network interfaces, by default unium listens on all of them. However, you might not necessarily have a network route from your browser to a given interface. Given the complexity of identifying the correct external interface, sometimes the tutorial scene displays the wrong IP address in the GUI.

This is what I would try ...

  *   Create a plain (development!) build with just the unium tutorial scene on the ios.
  *   Make sure all the settings haven't been changed from their defauls (port 8342, listening on all interfaces).
  *   Make sure the device is connected to your local wifi
  *   Find the IP address of your device from the OS settings (don't rely on unium displaying it correctly).
  *   On a computer connected to the same wifi goto http://<address>:8342/about

If that doesn't work, send me an example scene and device/ios/unity versions you're using and I'll take a look.


G


________________________________

**Comment by sanjusangal** [comment]
Hey Thanks. It works
