### ISSUE TITLE
HandlerUtils.cs failed to compile under Unity 2018.3.4f1

### ISSUE THREAD

**Issue by jgahide** [gwaredd/unium#32]
Hello, 
I may be wrong but I could not compile Unium under Unity 2018.3.4f1. 
I have an an issue with ScreenCapture.CaptureScreenshot( filename ); l 136 in HandlerUtils.cs.
I have looked in the history of the file and also looked for a custom implementation of ScreenCapture class, but found nothing.
So I think you are using the ScreenCapture class from Unity. Now it seems located inside UnityEngine. I had the code compile by changing :
ScreenCapture.CaptureScreenshot(filename); to 
UnityEngine.ScreenCapture.CaptureScreenshot(filename);

Regards,
Jerome.

**Comment by gwaredd** [comment]
I tried with 2018.3.5f1 and it compiles OK for me. UnityEngine is included at the top of the file so you shouldn't need the FQN so I don't think this is an issue :)
