### ISSUE TITLE
Work with device (android or ios) without manually get the IP address

### ISSUE THREAD

**Issue by yuewah** [gwaredd/unium#35]
In order to get the IP address of the android or ios device manually is not practical for fully automatic test.
If we can use adb forward tcp:8342 tcp:8342 (Android) or iproxy (iOS) , it will be easier. 
However, unium websocket or http cannot support adb forward.

**Comment by yuewah** [comment]
I found that it is because the Unium Server on the device is listening on public ip, adb forward is only work if it is listening on 127.0.0.1

**Comment by yuewah** [comment]
Use 0.0.0.0 works on editor and device for all localhost , public IP, and adb forward

**Comment by gwaredd** [comment]
Cool :)

On the UniumComponent, setting "**Serve On**" to "**All Interfaces**" should do that for you - it's the default setting, let me know if it doesn't work.

**Comment by yuewah** [comment]
it works, thank you
