### ISSUE TITLE
Unium socket bind failed on IL2CPP platform

### ISSUE THREAD

**Issue by yuewah** [gwaredd/unium#37]
Unity 2017.4.x, .Net 2.0 Subset
class EventListener 
eventInfo.AddEventHandler is not working on IL2CPP (e.g. iOS ), but work on Mono and Editor

https://issuetracker.unity3d.com/issues/error-adding-a-delegate-using-eventinfo-dot-addeventhandler-on-aot-targets

**Comment by gwaredd** [comment]
I'll take a look, however if this is an issue with unity the options for a work-around maybe limited :) I notice that issue is flagged as "by design".

Out of interest, have you tried ".NET 4.x Equivalent" and is it still an issue?

**Comment by yuewah** [comment]
you are right, It works on Unity 2018.3.x, .NET 4.x Equivalent

**Comment by yuewah** [comment]
However, it works on Unity 2018.3.x, .NET 3.5 too

**Comment by gwaredd** [comment]
In the version that doesn't work, have you tried ...

```eventInfo.GetAddMethod().Invoke( Target, new [] { Delegate } );```

Rather than ...

```eventInfo.AddEventHandler( Target, Delegate );```

Same thing, different execution path :)

**Comment by yuewah** [comment]
Excellent, it works

**Comment by gwaredd** [comment]
Awesome.

This is a bug in the IL2CPP compiler for that version of Unity, so not something unium related ;)
