### ISSUE TITLE
the format of scene hierarchy tree json show  on the webpage is wrong

### ISSUE THREAD

**Issue by kongguliu** [gwaredd/unium#38]
The scene hierarchy tree has been obtained, but the format displayed on the web page is incorrect.
the format show on the webpage likes this:
"[{\"name\":\"Sphere\",\"tag\":\"Untagged\",\"activeInHierarchy\":true,\"components\":[\"Transform\",\"MeshFilter\",\"MeshRenderer\",\"SphereCollider\"],\"children\":[\"Cube\",\"children\":[],\"Cube (1)\",\"children\":[\"Sphere (2)\",\"children\":[\"Cube\",\"children\":[],\"Cube (1)\",\"children\":[]]]]}]"
![image](https://user-images.githubusercontent.com/18191658/55866362-c8a3e000-5bb2-11e9-80d0-7f3e83ea09ef.png)
![image](https://user-images.githubusercontent.com/18191658/55866377-cfcaee00-5bb2-11e9-8e73-fd51f3571f30.png)

**Comment by gwaredd** [comment]
Yes, that isn't valid JSON. How are you obtaining the hierarchy?

The code above isn't part of the unium library (there is no `SetChildren` function for example).

**Comment by gwaredd** [comment]
So this looks like you are trying to add this feature yourself to the code, in which case your use of the `JsonBuilder` object is wrong.

Inside `SetChildren` you want something like ...

```cs
json.BeginObject();
json.Name( "name" );
json.Value( c.name );

if( c.transform != null )
{
  // ... etc
}

json.EndObject();
```

Alternatively, you can get the hierarchy as a list by executing the query `/q/scene//*.path`

This will return all objects in the hierarchy as a list (see [https://github.com/gwaredd/unium/issues/13](Issue 13))

Alternatively, passing a depth of -1 into `JsonReflector.Recurse()` should turn on full recursion of the hierachy.

HTH, Gw

**Comment by kongguliu** [comment]
> Yes, that isn't valid JSON. How are you obtaining the hierarchy?
> 
> The code above isn't part of the unium library (there is no `SetChildren` function for example).

i wrote the SetChildren in the UnitySerialisers.cs,a part of SerialiseGameObject,you can see two photos,i have got the scene hierarchy tree.
![image](https://user-images.githubusercontent.com/18191658/55869122-75cd2700-5bb8-11e9-98f6-5a02e360307d.png)
![image](https://user-images.githubusercontent.com/18191658/55869130-7b2a7180-5bb8-11e9-923a-9fe3b50f6c8f.png)
![image](https://user-images.githubusercontent.com/18191658/55869153-88dff700-5bb8-11e9-8467-ee15185b817b.png)
