### ISSUE TITLE
automatically clicked the button

### ISSUE THREAD

**Issue by kongguliu** [gwaredd/unium#39]
Is it possible to control the button so that it is automatically clicked, and if so, how is it implemented?

**Comment by gwaredd** [comment]
The best way it to call the onClick() function directly on the button component. 

For example
 `/q/scene/Canvas/MyButton.Button.onClick.Invoke()`

Alternatively, you can simulate a mouse click at a given position with `/q/simulate.click(20,600)`

This sends an IPointerDown message using the event system, which isn't perfect but should work for standard unity ui elements

**Comment by kongguliu** [comment]
> The best way it to call the onClick() function directly on the button component.
> 
> For example
> `/q/scene/Canvas/MyButton.Button.onClick.Invoke()`
> 
> Alternatively, you can simulate a mouse click at a given position with `/q/simulate.click(20,600)`
> 
> This sends an IPointerDown message using the event system, which isn't perfect but should work for standard unity ui elements

Button.onClick.Invoke() worked success，thanks！

**Comment by gwaredd** [comment]
Update: With the latest code you no longer need the `.Invoke()` part.

`Button.onClick()` will also work
