### ISSUE TITLE
assert whether the operation was successful

### ISSUE THREAD

**Issue by kongguliu** [gwaredd/unium#40]
How to deny whether the interface switches after clicking the button, whether some UI elements are switched, hidden, modified attribute values, whether the object is destroyed, and whether the scene is loaded. Output test report (assertion) to text

**Comment by gwaredd** [comment]
If I understand, you are trying to test whether clicking a button was successful? I assume you are running your tests remotely using a testing framework (e.g. pytest, mocha, nunit, or whatever).

It would be helpful if you have a specific example of scene and test framework to help you with. Otherwise, generally ... 

Call the button.invoke() and wait for the HTTP request to finished then ...

You can test to see if an object has been destroyed by querying the hierarchy for the presence of the object, e.g. `/q/scene/Some/Object` - if this returns `[]` then it wasn't found.

You can test to see if it is active with by looking at the `activeInHierarchy` field for example `/q/scene/Some/Object.activeInHierarchy`

Same with any attributes you expect to have changed.

For loading a scene, the easiest way if to wait for a given length of time then see what the current scene is (using something like `/about` or `/q/scene/[0].scene.path`);

The more advanced way is to use websockets and bind to the `sceneLoaded` event

```
{"id":"sceneLoaded","q":"/bind/events.sceneLoaded"}
```

Then you will get a message when a new scene is loaded.

HTH

**Comment by kongguliu** [comment]
> If I understand, you are trying to test whether clicking a button was successful? I assume you are running your tests remotely using a testing framework (e.g. pytest, mocha, nunit, or whatever).
> 
> It would be helpful if you have a specific example of scene and test framework to help you with. Otherwise, generally ...
> 
> Call the button.invoke() and wait for the HTTP request to finished then ...
> 
> You can test to see if an object has been destroyed by querying the hierarchy for the presence of the object, e.g. `/q/scene/Some/Object` - if this returns `[]` then it wasn't found.
> 
> You can test to see if it is active with by looking at the `activeInHierarchy` field for example `/q/scene/Some/Object.activeInHierarchy`
> 
> Same with any attributes you expect to have changed.
> 
> For loading a scene, the easiest way if to wait for a given length of time then see what the current scene is (using something like `/about` or `/q/scene/[0].scene.path`);
> 
> The more advanced way is to use websockets and bind to the `sceneLoaded` event
> 
> ```
> {"id":"sceneLoaded","q":"/bind/events.sceneLoaded"}
> ```
> Then you will get a message when a new scene is loaded.
> 
> HTH

I want to output the query results, such as the UI tree, attribute values to txt, where should I add the code,  the JavaScript? Or where?

**Comment by kongguliu** [comment]
> .invoke() a

How to input a  text into an inputField, like thi,:http://localhost:8342/q/scene/Canvas/UIManager/win_login/input/Accout/InputField/text.Text='20180001',but this is not successful
![image](https://user-images.githubusercontent.com/18191658/56272484-5a6c9980-612d-11e9-977a-85e3beed03fb.png)

**Comment by gwaredd** [comment]
Try **Text.Text.text**

`http://localhost:8342/q/scene/Canvas/UIManager/win_login/input/Accout/InputField/Text.Text.text='20180001`

First Text is the game object
Second Text the component
Then text is the field

**Comment by kongguliu** [comment]
> Try **Text.Text.text**
> 
> `http://localhost:8342/q/scene/Canvas/UIManager/win_login/input/Accout/InputField/Text.Text.text='20180001`
> 
> First Text is the game object
> Second Text the component
> Then text is the field

this is not successful!

**Comment by gwaredd** [comment]
> I want to output the query results, such as the UI tree, attribute values to txt, where should I add the code, the JavaScript? Or where?

Javascript `console.log()` would seem appropriate, assuming this is for development (either in browser or from node.js).

**Comment by gwaredd** [comment]
> > Try **Text.Text.text**
> > `http://localhost:8342/q/scene/Canvas/UIManager/win_login/input/Accout/InputField/Text.Text.text='20180001`
> 
> this is not successful!

If you run the unium tutorial scene, you should see an IP address in the top left. You can change the displayed text with the following query,

```
    http://localhost:8342/q/scene/UI/IPAddress.Text.text=hello
```

Check this works for you ...

**Comment by kongguliu** [comment]
> > > Try **Text.Text.text**
> > > `http://localhost:8342/q/scene/Canvas/UIManager/win_login/input/Accout/InputField/Text.Text.text='20180001`
> > 
> > 
> > this is not successful!
> 
> If you run the unium tutorial scene, you should see an IP address in the top left. You can change the displayed text with the following query,
> 
> ```
>     http://localhost:8342/q/scene/UI/IPAddress.Text.text=hello
> ```
> Check this works for you ...

Strange,it is not in the tutorial scene,the query http://localhost:8342/q/scene/Canvas/UIManager/win_login/Text.Text.text=hello,it is successful.
but the query
http://localhost:8342/q/scene/Canvas/UIManager/win_login/input/Account/InputField/Text.Text.text=hello,it is not successful.

**Comment by gwaredd** [comment]
What is returned by the unsuccessful query?

**Comment by kongguliu** [comment]
> What is returned by the unsuccessful query?

![image](https://user-images.githubusercontent.com/18191658/56276088-7aec2200-6134-11e9-96a1-c65633501946.png)

**Comment by gwaredd** [comment]
The empty array `[]` means no objects were matched by that query.

Easiest way to find what's failing is maybe to strart with something that works and try adding bits until it fails, e.g. ...

```
http://localhost:8342/q/scene/Canvas/UIManager/win_login/input
http://localhost:8342/q/scene/Canvas/UIManager/win_login/input/Account/InputField/Text
http://localhost:8342/q/scene/Canvas/UIManager/win_login/input/Account/InputField/Text.Text
http://localhost:8342/q/scene/Canvas/UIManager/win_login/input/Account/InputField/Text.Text.text
http://localhost:8342/q/scene/Canvas/UIManager/win_login/input/Account/InputField/Text.Text.text=hello
```

**Comment by kongguliu** [comment]
> The empty array `[]` means no objects were matched by that query.
> 
> Easiest way to find what's failing is maybe to start with something that works and try adding bits until it fails, e.g. ...
> 
> ```
> http://localhost:8342/q/scene/Canvas/UIManager/win_login/input
> http://localhost:8342/q/scene/Canvas/UIManager/win_login/input/Account
> http://localhost:8342/q/scene/Canvas/UIManager/win_login/input/Account/InputField
> http://localhost:8342/q/scene/Canvas/UIManager/win_login/input/Account/InputField/Text
> http://localhost:8342/q/scene/Canvas/UIManager/win_login/inpu/Account/InputField/Text.Text
> http://localhost:8342/q/scene/Canvas/UIManager/win_login/input/Account/InputField/Text.Text.text
> http://localhost:8342/q/scene/Canvas/UIManager/win_login/input/Account/InputField/Text.Text.text=hello
> ```

Sorry,the unsuccessful query returned this 
![image](https://user-images.githubusercontent.com/18191658/56277199-7c1e4e80-6136-11e9-9e35-dc2cab99c4cc.png)

**Comment by gwaredd** [comment]
So either the value it is trying to set it empty (which is unlikely), or the value can't be changed , in which case it is unity related.

You can put a [breakpoint here](https://github.com/gwaredd/unium/blob/d1690e367e09691e451432566321535850e18d81/Assets/Unium/GQL/Query/ActionSet.cs#L45) to step through the code and see what's going on.

**Comment by kongguliu** [comment]
> So either the value it is trying to set it empty (which is unlikely), or the value can't be changed , in which case it is unity related.

Whether because the text is inside a inputField,not just a text.

**Comment by gwaredd** [comment]
Possibly yes, can you change the value on the InputField instead?

`http://localhost:8342/q/scene/Canvas/UIManager/win_login/input/Account/InputField.text=hello`

or 

`http://localhost:8342/q/scene/Canvas/UIManager/win_login/input/Account/InputField.SetTextWithoutNotify(hello)`

**Comment by kongguliu** [comment]
> Possibly yes, can you change the value on the InputField instead?
> 
> `http://localhost:8342/q/scene/Canvas/UIManager/win_login/input/Account/InputField.text=hello`
> 
> or
> 
> `http://localhost:8342/q/scene/Canvas/UIManager/win_login/input/Account/InputField.SetTextWithoutNotify(hello)`

both were unsccessful

**Comment by gwaredd** [comment]
Oops, I meant `InputField.InputField` :)

http://localhost:8342/q/scene/Canvas/UIManager/win_login/input/Account/InputField.InputField.text=hello

**Comment by kongguliu** [comment]
> http://localhost:8342/q/scene/Canvas/UIManager/win_login/input/Account/InputField.InputField.text=hello

successful ,thank you very much!

**Comment by kongguliu** [comment]
> > I want to output the query results, such as the UI tree, attribute values to txt, where should I add the code, the JavaScript? Or where?
> 
> Javascript `console.log()` would seem appropriate, assuming this is for development (either in browser or from node.js).

I want to output the returned array to a text instead of displaying it on a webpage or JavaScript console. Where should  I add the code to a specific location in tutorial.js

**Comment by kongguliu** [comment]
> If I understand, you are trying to test whether clicking a button was successful? I assume you are running your tests remotely using a testing framework (e.g. pytest, mocha, nunit, or whatever).
> 
> It would be helpful if you have a specific example of scene and test framework to help you with. Otherwise, generally ...
> 
> Call the button.invoke() and wait for the HTTP request to finished then ...
> 
> You can test to see if an object has been destroyed by querying the hierarchy for the presence of the object, e.g. `/q/scene/Some/Object` - if this returns `[]` then it wasn't found.
> 
> You can test to see if it is active with by looking at the `activeInHierarchy` field for example `/q/scene/Some/Object.activeInHierarchy`
> 
> Same with any attributes you expect to have changed.
> 
> For loading a scene, the easiest way if to wait for a given length of time then see what the current scene is (using something like `/about` or `/q/scene/[0].scene.path`);
> 
> The more advanced way is to use websockets and bind to the `sceneLoaded` event
> 
> ```
> {"id":"sceneLoaded","q":"/bind/events.sceneLoaded"}
> ```
> Then you will get a message when a new scene is loaded.
> 
> HTH

I used http://localhost:8342/q/scene/about,it returned empty array[],used http://localhost:8342/q/scene/[0].scene.path,returned "Assets/Scenes/Game.unity".
And I don't know where to add or change the code with  {"id":"sceneLoaded","q":"/bind/events.sceneLoaded"}

**Comment by gwaredd** [comment]
The route for about is `http://localhost:8342/about` (not /q/scene - its not a query :)

If you have multiple scenes `http://localhost:8342/q/scene/*.scene.path` will return all of them although it may give you multiple results as it's technically just returning the scenes of the top level objects (or scene.name if you just want the name rather than the path).

Binding to events requires the websocket interface which I don't believe you're using.
