### ISSUE TITLE
how to use take screenshot

### ISSUE THREAD

**Issue by kongguliu** [gwaredd/unium#41]
i create an empty object(named GameObject) ,with third person camera script,target is GameObject,but it has a wrong when run the scene.
![image](https://user-images.githubusercontent.com/18191658/56281759-ff906d80-613f-11e9-94da-445fd10b03cc.png)

**Comment by gwaredd** [comment]
The third person camera code from the tutorial was really just intended for the tutorial not for production use :) The take screenshot functionality will work with whatever cameras are active in the scene - `/utils/appscreenshot` just calls [ScreenCapture.CaptureScreenshot](https://docs.unity3d.com/ScriptReference/ScreenCapture.CaptureScreenshot.html) under-the-hood.

However, the TPC camera code relies on the camera being tagged as the MainCamera, which is probably the error you are seeing.

<img width="224" alt="camera" src="https://user-images.githubusercontent.com/533262/56355200-9fe0a380-61cd-11e9-9460-1914c1ab8c27.png">

**Comment by kongguliu** [comment]
> The third person camera code from the tutorial was really just intended for the tutorial not for production use :) The take screenshot functionality will work with whatever cameras are active in the scene - `/utils/appscreenshot` just calls [ScreenCapture.CaptureScreenshot](https://docs.unity3d.com/ScriptReference/ScreenCapture.CaptureScreenshot.html) under-the-hood.
> 
> However, the TPC camera code relies on the camera being tagged as the MainCamera, which is probably the error you are seeing.
> 
> <img alt="camera" width="224" src="https://user-images.githubusercontent.com/533262/56355200-9fe0a380-61cd-11e9-9460-1914c1ab8c27.png">

I understood it.but the photo is reverse，
![image](https://user-images.githubusercontent.com/18191658/56402824-8012b380-6291-11e9-8cb2-b64f783e2667.png)
![image](https://user-images.githubusercontent.com/18191658/56402849-991b6480-6291-11e9-9439-c1b7aa4da9f3.png)
