### ISSUE TITLE
can it work on webGL platform?

### ISSUE THREAD

**Issue by kongguliu** [gwaredd/unium#42]
I packaged the unity project, it was a webGL,with  ​Development Build​ is 
true then I opened the project on the webpage, and the unium homepage did not open.
And,on the PC platform,the unium homepage opened,but can't find the web,the web was wrong.
![image](https://user-images.githubusercontent.com/18191658/56350747-0e3d5a00-61fe-11e9-8cae-5fc7b51400b4.png)
![20190418175718](https://user-images.githubusercontent.com/18191658/56353204-780c3280-6203-11e9-8edf-558da6a1b75d.jpg)

**Comment by gwaredd** [comment]
The short answer is no, it is not supported in WebGL builds.

This is because it works by creating a server (listening socket) which is not supported by browsers, as this would be a security risk.

The longer answer is, it could possibly be made to work in WebGL builds by either adding WebRTC support or websockets that 'call home'. However, both approaches would require significant work beyond the current remit.

**Comment by kongguliu** [comment]
> The short answer is no, it is not supported in WebGL builds.
> 
> This is because it works by creating a server (listening socket) which is not supported by browsers, as this would be a security risk.
> 
> The longer answer is, it could possibly be made to work in WebGL builds by either adding WebRTC support or websockets that 'call home'. However, both approaches would require significant work beyond the current remit.

Whether it support on the PC platform,I run the .exe,the unium homepage opened,but can't find the web,the web was wrong.

**Comment by kongguliu** [comment]
> The short answer is no, it is not supported in WebGL builds.
> 
> This is because it works by creating a server (listening socket) which is not supported by browsers, as this would be a security risk.
> 
> The longer answer is, it could possibly be made to work in WebGL builds by either adding WebRTC support or websockets that 'call home'. However, both approaches would require significant work beyond the current remit.

hello?I build the tutorial worked on the PC,but the unium can't open the unium home page.
![image](https://user-images.githubusercontent.com/18191658/56480697-da0fb500-64ed-11e9-9bf0-33e97ed0e342.png)
![image](https://user-images.githubusercontent.com/18191658/56480704-e136c300-64ed-11e9-9958-f2138b210ba3.png)

**Comment by gwaredd** [comment]
It looks like your build is missing the StreamingAssets folder.

However, this isn't required for unium, you can go directly to the URL, eg

http://localhost:8342/about

**Comment by kongguliu** [comment]
> It looks like your build is missing the StreamingAssets folder.
> 
> However, this isn't required for unium, you can go directly to the URL, eg
> 
> http://localhost:8342/about


No, it actually has StreamingAssets folder,and any URL can't open the webpage.

![image](https://user-images.githubusercontent.com/18191658/56494545-3215de00-6525-11e9-9543-19c570cfb0cd.png)
![image](https://user-images.githubusercontent.com/18191658/56494563-3c37dc80-6525-11e9-9ff3-816766e10b89.png)

**Comment by gwaredd** [comment]
If the game is running and you go to `http://localhost:8342/about` in your browser, what does it return? (If you look at the network tab in the browser tools).

Does it return an error (like 404 or 500) or does it time out?

**Comment by kongguliu** [comment]
> If the game is running and you go to `http://localhost:8342/about` in your browser, what does it return? (If you look at the network tab in the browser tools).
> 
> Does it return an error (like 404 or 500) or does it time out?

It was 404

**Comment by gwaredd** [comment]
This works OK for me.

I would double check you have the "development build" flag checked and that your firewall isn't blocking the port.

However, if it is returning 404 then that suggests you can connect to the port and the issue is with your code.

**Comment by kongguliu** [comment]
All the firewall had closed,and the development build flag was true.But I don't know why it can't work successful.
![image](https://user-images.githubusercontent.com/18191658/56571750-2f33ef80-65f0-11e9-846d-72c48300c7aa.png)
Can you send the build to me? I want to see how it work. My email:1131087670@qq.com
