### ISSUE TITLE
Full feature mobile UI automation tool.

### ISSUE THREAD

**Issue by yuewah** [gwaredd/unium#45]
There is a full feature mobile game automation tool called airtest that use a opensource library called Poco. It has free IDE to create test script, however, it use tcp socket for communication.
http://airtest.netease.com/

I like unium as it use restful and websocket.

**Comment by gwaredd** [comment]
Hey, yes I've seen airtest, it looks pretty cool thanks for pointing it out :)

Glad you like Unium, it's not a 'fully featured all in one' testing tool like airtest - rather gives you a way to hook up your preferred tools, like in [this video](https://youtu.be/UbPk2VljW78).
