### ISSUE TITLE
how to change the main camera or player rotation?

### ISSUE THREAD

**Issue by kongguliu** [gwaredd/unium#46]
I want to change the  main camera or player rotation,but it does't work,with url:
http://localhost:8342/q/scene//Player.Transform.rotation={'x':0,'y':-86,'z':0}

**Comment by gwaredd** [comment]
Transform.rotation is a Quaternion, you might like to try [euler angles](https://docs.unity3d.com/ScriptReference/Transform-eulerAngles.html) instead ...

`http://localhost:8342/q/scene//Player.Transform.eulerAngles={'x':0,'y':-86,'z':0}`

However, to pass anything other than a primitive type or Vector3 wasn't supported in unium. I've [made a change](https://github.com/gwaredd/unium/commit/5839c127cc053ed4b0bc88b8792098dec2c98c71) which should work with Quaternions (and other serialisable objects) which should fix this for you.
