### ISSUE TITLE
trigger an event

### ISSUE THREAD

**Issue by hkklearn** [gwaredd/unium#48]
is it possible to trigger an event?

**Comment by gwaredd** [comment]
Hey, triggering events is not supported through GQL currently.

The most expedient way to get something working is to add a function that does what you need and invoke that instead.

However, it should be relatively straight forward to extend the [invoke action](https://github.com/gwaredd/unium/blob/94a320638c58e265a12cc6047c976bf223c7e584/Assets/Unium/GQL/Query/ActionInvoke.cs#L39) code to support events as well as methods. I will look at adding this when I find some time.

**Comment by gwaredd** [comment]
[This branch](https://github.com/gwaredd/unium/tree/feature/triggering_events) allows events to be triggered the same as you would functions. I'll merge it into master once it's more thoroughly tested.
