### ISSUE TITLE
websocket not work in il2cpp

### ISSUE THREAD

**Issue by yuewah** [gwaredd/unium#5]
I tested on unity5.6.x with il2cpp android build 
when connect using websocket, it close the connection immediately.

12-16 12:12:17.267: I/Unity(1037): Listening on 172.16.247.102:8342
12-16 12:12:17.267: I/Unity(1037):  
12-16 12:12:17.267: I/Unity(1037): (Filename: ./artifacts/generated/Android/runtime/DebugBindings.gen.cpp Line: 51)
12-16 12:12:17.267: I/Unity(1037): [unium][0] server listening on 172.16.247.102:8342
12-16 12:12:17.267: I/Unity(1037):  
12-16 12:12:17.267: I/Unity(1037): (Filename: ./artifacts/generated/Android/runtime/DebugBindings.gen.cpp Line: 51)
12-16 12:12:17.297: D/Unity(1037): Sensor :        Accelerometer ( 1) ; 0.009577 / 0.01s ; BMC150 Acceleration Sensor / Bosch Sensortec 
12-16 12:12:17.317: D/Unity(1037): Choreographer available: Enabling VSYNC timing
12-16 12:12:17.337: D/Unity(1037): Setting up 1 worker threads for Enlighten.
12-16 12:12:17.337: D/Unity(1037):   Thread -> id: ffffffffb841f3f8 -> priority: 1 
12-16 12:12:17.337: D/Unity(1037): ANativeWindow: (720/1280) RequestedResolution: (0/0) EGLSurface: (720/1280)
12-16 12:12:23.747: I/Unity(1037): [0] OPEN /ws - 172.16.252.127:37437
12-16 12:12:23.747: I/Unity(1037):  
12-16 12:12:23.747: I/Unity(1037): (Filename: ./artifacts/generated/Android/runtime/DebugBindings.gen.cpp Line: 51)
12-16 12:12:23.757: I/Unity(1037): [unium][1] [sock:0] connected - /ws
12-16 12:12:23.757: I/Unity(1037):  
12-16 12:12:23.757: I/Unity(1037): (Filename: ./artifacts/generated/Android/runtime/DebugBindings.gen.cpp Line: 51)
12-16 12:12:23.767: I/Unity(1037): [ws:0] Opening websocket id:0
12-16 12:12:23.767: I/Unity(1037):  
12-16 12:12:23.767: I/Unity(1037): (Filename: ./artifacts/generated/Android/runtime/DebugBindings.gen.cpp Line: 51)
12-16 12:12:24.787: E/Unity(1037): [ws:0] Fatal error -   at System.Net.Sockets.NetworkStream.EndRead (IAsyncResult ar) [0x00000] in <filename unknown>:0 
12-16 12:12:24.787: E/Unity(1037):   at gw.proto.http.WebSocket.OnRead (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
12-16 12:12:24.787: E/Unity(1037):   at System.Net.Sockets.Socket+SocketAsyncResult.Complete () [0x00000] in <filename unknown>:0 
12-16 12:12:24.787: E/Unity(1037):  
12-16 12:12:24.787: E/Unity(1037): (Filename: ./artifacts/generated/Android/runtime/DebugBindings.gen.cpp Line: 51)
12-16 12:12:24.787: E/Unity(1037): [ws:0] Terminating connection - System.IO.IOException: EndRead failure ---> System.Net.Sockets.SocketException: Operation on non-blocking socket would block
12-16 12:12:24.787: E/Unity(1037):   at System.Net.Sockets.Socket+SocketAsyncResult.CheckIfThrowDelayedException () [0x00000] in <filename unknown>:0 
12-16 12:12:24.787: E/Unity(1037):   at System.Net.Sockets.Socket.EndReceive (IAsyncResult asyncResult, SocketError& errorCode) [0x00000] in <filename unknown>:0 
12-16 12:12:24.787: E/Unity(1037):   at System.Net.Sockets.NetworkStream.EndRead (IAsyncResult ar) [0x00000] in <filename unknown>:0 
12-16 12:12:24.787: E/Unity(1037):   at gw.proto.http.WebSocket.OnRead (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
12-16 12:12:24.787: E/Unity(1037):   at System.Net.Sockets.Socket+SocketAsyncResult.Complete () [0x00000] in <filename unknown>:0 
12-16 12:12:24.787: E/Unity(1037):   --- End of inner exception stack trace ---
12-16 12:12:24.787: E/Unity(1037):   at System.Net.Sockets.NetworkStream.EndRead (IAsyncResult ar) [0x00000] in <filename unknown>:0 
12-16 12:12:24.787: E/Unity(1037):   at gw.proto.http.WebSocket.OnRead (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
12-16 12:12:24.787: E/Unity(1037):   at System.Net.Sockets.Socket+SocketAsyncResult.Complete () [0x00000] in <filename unk
12-16 12:12:24.787: I/Unity(1037): [ws:0] Connection closed
12-16 12:12:24.787: I/Unity(1037):  
12-16 12:12:24.787: I/Unity(1037): (Filename: ./artifacts/generated/Android/runtime/DebugBindings.gen.cpp Line: 51)
12-16 12:12:24.787: I/Unity(1037): [unium][2] [sock:0] closed

**Comment by gwaredd** [comment]
This isn't something I've seen before, I will try and get a repro.

- I presume normal REST requests work OK?
- Which version of the Android NDK are you using?
- Is this before or after you send any data over the socket?

Thanks

Gw

**Comment by yuewah** [comment]
1. Yes
2. NDK r10e
3. Before, I just connect using the Unium Socket Explorer

**Comment by gwaredd** [comment]
I've checked in a fix, see if that helps.

As far as I can tell the IL2CPP version of the TcpClient has different timeout behaviour from the C# documentation. Explicitly setting the timeout values seems to work.

**Comment by yuewah** [comment]
I am sorry, it doesn't help with another error.
12-20 10:01:36.165: E/Unity(4814): System.Net.Sockets.SocketException: System call failed
12-20 10:01:36.165: E/Unity(4814):   at System.Net.Sockets.Socket.SetSocketOption (SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue) [0x00000] in <filename unknown>:0 
12-20 10:01:36.165: E/Unity(4814):   at System.Net.Sockets.TcpClient.set_ReceiveTimeout (Int32 value) [0x00000] in <filename unknown>:0 
12-20 10:01:36.165: E/Unity(4814):   at gw.proto.http.Server.OnAcceptConnection (IAsyncResult result) [0x00000] in <filename unknown>:0 
12-20 10:01:36.165: E/Unity(4814):   at System.Net.Sockets.Socket+SocketAsyncResult.Complete () [0x00000] in <filename unknown>:0

**Comment by gwaredd** [comment]
OK, I have reproduced the error and have, hopefully, a fix. Let me know if that works.

Gw

**Comment by yuewah** [comment]
I work now....thank you very much...it help a lot.

**Comment by yuewah** [comment]
oh, when I try fps_graph, the connection closed for a while randomly.

**Comment by yuewah** [comment]
Can you reproduce the problem?

**Comment by gwaredd** [comment]
I've had a quick look and it's possibly something to do with the websocket ping/pong on android. 

Could you try commenting out the contents of the Tick() function in [WebSocket.cs](https://github.com/gwaredd/unium/blob/eddf7287d5743bc9c01053d7b7c25e322be31683/Assets/Unium/Core/gw.proto.http/WebSocket.cs#L192) and see if that fixes it?

I'll see if I have sometime to debug it properly next week.

**Comment by yuewah** [comment]
oh, it fixes , thanks.

**Comment by gwaredd** [comment]
FYI - I've checked in some changes that should fix it.

Cheers
