### ISSUE TITLE
Unity package import doesn't work due to missing meta-file

### ISSUE THREAD

**Issue by CKehl** [gwaredd/unium#61]
Hi,

I really like the Unium framework of yours for UI testing and I wanna include it in my university projects. Now, I tried to import Unium via the package.json, which you added a couple of days ago. Works nearly okay, but you are missing a package.json.meta in your Packages-folder. So, when I import the Unium package, I get an error in Unity saying:

Read only asset Packages/com.gwaredd.unium/package.json has no meta file.
System.Reflection.MethodBase:Invoke(Object, Object[])
JetBrains.Rider.Unity.Editor.UnityUtils:SyncSolution()
JetBrains.Rider.Unity.Editor.PluginEntryPoint:SyncSolutionOnceCallBack()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

Could you fix that for some later commits ? It's not super-urgent, but I'd really like to import your work in my projects and that needs to use the package method because of the CI pipeline.

Thanks a lot, Great work you did,

Christian

**Comment by gwaredd** [comment]
Hey, I'm glad you like it.

Apologies, that file wasn't meant to be checked into the master branch. I was in the middle of refactoring the file structure to make it compatible with the unity package manager. I will at some point push those commits, then the library should be easier to use in projects.

Gw

**Comment by CKehl** [comment]
Cool, I'll be waiting to see it then at some point. Very exciting.

**Comment by starikcetin** [comment]
> Hey, I'm glad you like it.
> 
> Apologies, that file wasn't meant to be checked into the master branch. I was in the middle of refactoring the file structure to make it compatible with the unity package manager. I will at some point push those commits, then the library should be easier to use in projects.
> 
> Gw

I would love you to add it to [awesome-upm](https://github.com/starikcetin/awesome-upm) once you are done. 

Also, check out my command-line tool for automating upm releases for git repos: https://github.com/starikcetin/git-upm-publisher

It basically tries to automate the process described here: https://www.patreon.com/posts/25070968

**Comment by lacostej** [comment]
See also https://openupm.com/ for a directory of unity OSS packages.

**Comment by gwaredd** [comment]
I've split out the subtree and tagged it as `1.0.4`. This should work for upm and openupm, I'll update the readme at a later date - however ...

From the command line ...
```
git clone --branch 1.0.4 https://github.com/gwaredd/unium.git
```
Or in a manifest file ...
```
{
 "dependencies": {
     "com.gwaredd.unium": "https://github.com/gwaredd/unium.git#1.0.4",
     ...
 },
}
```

**Comment by lacostej** [comment]
Note that I just discovered this hidden feature which allows to make it work with a subpath in the repo: https://forum.unity.com/threads/some-feedback-on-package-manager-git-support.743345/#post-5425311

**Comment by lacostej** [comment]
thanks for the changes :)
