### ISSUE TITLE
Cloned object paths cannot be resolved

### ISSUE THREAD

**Issue by simonjeesam** [gwaredd/unium#62]
If you have a cloned GameObject with the name like "MyGO(Clone)" then when trying to just reference that by its path I get an error:

GQL::Query - failed to parse query, no attribute to set

Looking at the regex code it looks like it's taking the () brackets as an indication that it's an action (method invoke?) query when all I'm actually trying to do is get that GO's info.

**Comment by gwaredd** [comment]
By design, unium interprets parenthesis as an invoke action.

You can work around this with wildcards, e.g. `MyGO*Clone*`

A better solution maybe to allow you to escape them. If you wanted to have a go at add this to the parsing and create a pull request I can review it ;)

**Comment by simonjeesam** [comment]
@gwaredd Sure, understood. I thought that might be the case. I tried escaping them but that didn't work. I'll try changing the regex parsing. Thanks!

**Comment by lacostej** [comment]
```/q//*[name='MyGO(Clone)']``` works I think

**Comment by gwaredd** [comment]
sneaky ;)

**Comment by jgitt** [comment]
> 
> 
> By design, unium interprets parenthesis as an invoke action.
> 
> You can work around this with wildcards, e.g. `MyGO*Clone*`
> 
> A better solution maybe to allow you to escape them. If you wanted to have a go at add this to the parsing and create a pull request I can review it ;)

Is it possible for that to be an invoke action, though? Wouldn't it need to be something like `MyGO(Clone).Component.myFunction()`? From my understanding, `MyGO(Clone)` can only be a reference to a game object since there is no dot notation to access the function.

**Comment by gwaredd** [comment]
Yes you're correct. A function invocation can only happen on an attribute (after a dot), further it can only be the last dot as it needs to be at the end (we don't call functions mid query).

So the bit that parsers the query could figure it out if it was a bit more clever ;)

**Comment by jgitt** [comment]
I'm not that experienced with regex (or c#/unity for that matter) but I think I'm close to having something working. I can make a pull request once I'm done if you'd like.

**Comment by gwaredd** [comment]
Sounds great :) Create a pull request and I'll review it
