### ISSUE TITLE
Automate tap/click a toggle button

### ISSUE THREAD

**Issue by juunishimaster** [gwaredd/unium#68]
While it's possible to automate click button, is there a way to automate a "click" on toggle button?

**Comment by gwaredd** [comment]
Setting `isOn=true` or `isOn=false` should work. I don't know if there's a way to toggle the state from code, but you could always read the value first and do the toggle in script.

**Comment by juunishimaster** [comment]
Aaa, it works! Thank you so much for the quick response! I really owe you.
