### ISSUE TITLE
Obtaining an image or its filename

### ISSUE THREAD

**Issue by juunishimaster** [gwaredd/unium#72]
The thing I try to do: doing an automation based on a certain requirement which in the game shown as an image.

Is it possible in Unium to get the sprite/image or its filename on an Image component using Unium?

**Comment by gwaredd** [comment]
Well you *could* use the screenshot endpoint (`/utils/screenshot` ) and use something like [sikulix](http://www.sikulix.com/) to do image recognition but I don't think that's what you are asking.

It's not possible with current code. Unium does a reasonable job of reflecting general .net objects but you will need to enhance it a little to get the image data.

Easiest way if probably to add a new type handler/serialiser for a [Texture](https://docs.unity3d.com/ScriptReference/Texture.html), [to the list in Unium.cs](https://github.com/gwaredd/unium/blob/def92190ec025d8024ecb1ce5a8ca35a9544c666/Assets/Unium/Unium.cs#L43). See [SerialiseTransform ](https://github.com/gwaredd/unium/blob/def92190ec025d8024ecb1ce5a8ca35a9544c666/Assets/Unium/Core/UnitySerialisers.cs#L83) for an example. 

Then output the binary texture data as [base64](https://docs.microsoft.com/en-us/dotnet/api/system.convert.tobase64string?view=netframework-4.8).

Alternatively it might be possible to make the [base serialiser](https://github.com/gwaredd/unium/blob/def92190ec025d8024ecb1ce5a8ca35a9544c666/Assets/Unium/Core/gw.proto.utils/JsonSerialiser.cs#L55) automatically convert byte[] to a base64 string.

Not sure if unity stores filenames with Images, that more of a question for the Unity forums :)

**Comment by gwaredd** [comment]
FYI I've added a serialisers for a Hash128 object which may be useful here.

From a unity [Image](https://docs.unity3d.com/2019.1/Documentation/ScriptReference/UI.Image.html) you can get the underlying texture, name, hash and raw data. Something like ...
```
//Object.Image.mainTexture.name
//Object.Image.mainTexture.imageContentsHash
//Object.Image.mainTexture.GetRawTextureData()
```
