### ISSUE TITLE
automated_play not working correct

### ISSUE THREAD

**Issue by KosmoDED** [gwaredd/unium#75]
![image](https://user-images.githubusercontent.com/39064671/82124974-7d8fcf80-97ab-11ea-8725-28ba93badccb.png)

![image](https://user-images.githubusercontent.com/39064671/82124958-5cc77a00-97ab-11ea-8047-c18efe9626e7.png)

Reproduction steps:
1. Download commit df76f9d and open with Unity 2019.3.9f1
2. Run Tutorial scene
3. Open automated_play (http://localhost:8342/tutorial/automated_play.html)

**Comment by gwaredd** [comment]
Hey, this works for me using the same commit and unity version. I am curious as to what it is returning for you though.

Could you take a look at the websocket messages and let me know what you see? You can do this in your browser. For example in chrome open the developer tools, reload the page and select the `ws` request and take a look at the message ...

![2020-05-16 19_15_09-Unium Automated Play Example - Brave](https://user-images.githubusercontent.com/533262/82127268-19204080-97aa-11ea-9d04-da11d908a7a6.png)

**Comment by KosmoDED** [comment]
![image](https://user-images.githubusercontent.com/39064671/82156154-3e807d80-9882-11ea-807a-3519e560e80a.png)

**Comment by gwaredd** [comment]
My guess is the locale of your computer is set to a number format that uses a comma to separate the fractional and decimal portions? Like spanish or german?

Looks like the error is with the FPS and RunningTime. I'll take a look at using a culture invariant conversion.

**Comment by gwaredd** [comment]
Let me know if that helps

**Comment by KosmoDED** [comment]
Yes. It's working now. Thanks.
