### ISSUE TITLE
How to automate an application on android device using this framework ?

### ISSUE THREAD

**Issue by Vingithub93** [gwaredd/unium#8]
I have downloaded the framework and added it to my application, able to interact with the application from browser using GQL, by following all the steps as you have mentioned in the README file.

But when I build an apk file and install it on android device, How do I interact with the application installed on device using GQL.

And I am able to launch that application installed on device through Appium. But I don't know how to interact with that launched application using this framework.

I am new to this unity and unium framework, please help me with this. Thanks in advance

**Comment by gwaredd** [comment]
Hey. Most probably you haven't set the development flag when you created the build, if you set this then you can access the game in the same way via the IP address of the phone.

By default unium is disabled for release builds, you can also enable it for all builds by defining the UNIUM_ENABLE symbol in the project settings.

See also this [previous thread](https://github.com/gwaredd/unium/issues/3).
