### ISSUE TITLE
Maintenance of unium "API"

### ISSUE THREAD

**Issue by lacostej** [gwaredd/unium#85]
This is not an issue in the code per se, but a question on good practice.

How do you manage the maintenance of the scripts that interact with your code through unium?

E.g. do you document that some code is made public in order to be accessible by Unium?

**Comment by gwaredd** [comment]
I guess it's one of the drawbacks of white-box tests as you sometimes end up modifying code to accommodate. Usually to expose something that is nominally private but you want the test to be able to query.

At the very least I would comment the code or have a naming convention. In some cases where I have added custom test hook functions for convenience they have the conditional attribute so they are compiled out in non-test builds ... `[Conditional("TEST_HOOK")] void TestHook_DoSomething() { ... }` 

Generally it's something I try to avoid.

Have you guys found a good approach?

**Comment by lacostej** [comment]
> Have you guys found a good approach?

no good approach yet.

I don't mind the exposure of the methods, even in public builds, but as we don't usually don't treat product code in the same way as modules when it comes to API stability so there's always a risk someone modifying the names or visibility of these methods, then breaking something much later as we don't run all Unium scripts as part of our builds and with IDE not necessarily being all goods finding al references in "foreign" code.

I'll close this as it's not an issue per se. Thanks!

**Comment by gwaredd** [comment]
Ah yes, I see your problem. 

I guess you could add a custom attribute to everything required for the "API". Then before you run the tests you can scrape the assemblies for everything tagged with with the attribute and diff the list it against the manifest of expected things.

It wouldn't stop people changing things and breaking the tests but it would highlight the tests that need updating. You could probably get clever and scrape tests for their endpoints to generate a manifest per test automatically.

Just a thought. I've never tried this :)
