### ISSUE TITLE
How can I invoke an Event Trigger function?

### ISSUE THREAD

**Issue by testifyqa** [gwaredd/unium#98]
Hi there @gwaredd ,

Im evaluating Unium and I have run into an issue.

I am able to click on game objects that have the Button component with `gameObject.Button.onClick()`

However, for game objects that ALSO have an EventTrigger, I am having some trouble. If I do `gameObject.Button.onClick()` on a gameObject that also has an event trigger component. the click does not actually happen.

I am unsure how I can instead invoke the function in an Event Trigger?

if I do `gameObject.EventTrigger` I get an appropriate response.

Ive tried things like `gameObject.EventTrigger.onPointerDown()` but that isnt correct

Please see the screenshot of the game object properties, would really appreciate help on how to successfully click this gameObject -> https://imgur.com/a/XC9WuR6

Thanks!

**Comment by testifyqa** [comment]
Just to update, I figured this out by going up a GameObject where the RaceHUDView script is attached and doing `http://localhost:8342/q/scene/UI%20Root/RaceHudScreen.RaceHUDView.OnAutoButtonClicked()` 👍 
but if theres a way to do it via EventTrigger I would still be interested to know.

Thanks.

**Comment by gwaredd** [comment]
You can invoke the event functions on the EventTrigger component directly.

Note that [EventTrigger.OnPointerDown()](https://docs.unity3d.com/2018.3/Documentation/ScriptReference/EventSystems.EventTrigger.html) takes a `PointerEventData` as input. So you will probably have to pass a JSON object as the parameter, e.g. just `{}` should work.

Try ... `gameObject.EventTrigger.OnPointerDown({})`

**Comment by testifyqa** [comment]
Ah, knew it mustve been something simple. Thanks, this makes total sense now
